#!/bin/bash
#
# ------------------------------------------------------------------------------
# An iptables script that will initialise firewall rules.
# Tested for Ubuntu 16.04
# ------------------------------------------------------------------------------
IPT="/sbin/iptables"
IPT6="/sbin/ip6tables"
SSH_PORT=XXXX
HOME_IP=X.X.X.X

# Set default policies to "ACCEPT"
$IPT -P INPUT ACCEPT
$IPT -P FORWARD ACCEPT
$IPT -P OUTPUT ACCEPT

# Flush `nat` and `mangle` tables
# @TODO: CHECK THIS!!!!!!!!!!!!!!
$IPT -t nat -F
$IPT -t mangle -F


# Flush all chains: this will flush the selected chain or all the chains in the
# table if no chain is specified. Equivalent to deleting all the rules one by one.
$IPT -F

# Delete all non-default chains - equivalent to `--delete-chain`
$IPT -X

# Set default chain policies for IPv4 to allow access
$IPT -P INPUT DROP
$IPT -P FORWARD DROP
$IPT -P OUTPUT DROP

# This policy drops all IPv6 traffic
$IPT6 -P INPUT DROP
$IPT6 -P OUTPUT DROP
$IPT6 -P FORWARD DROP

# Create a LOGGING chain
$IPT -N LOGGING

# ------------------------------------------------------------------------------
# Rules
# ------------------------------------------------------------------------------

# Accept all established inbound connections: self protection - adding a new rule
# won't kill the connection. This rule makes use of the connection tracking extension.
$IPT -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
#$IPT -A OUTPUT -o -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

# Allow loopback access
$IPT -A INPUT -i lo -j ACCEPT
$IPT -A OUTPUT -o lo -j ACCEPT

# Drop invalid packets
$IPT -A INPUT -m state --state INVALID -j LOGGING

# Allow incoming SSH on the specified port. SSH output is allowed for an established connection
$IPT -A INPUT -i eth0 -p tcp --dport $SSH_PORT -m state --state NEW,ESTABLISHED -j ACCEPT
$IPT -A OUTPUT -o eth0 -p tcp --sport $SSH_PORT -m state --state ESTABLISHED -j ACCEPT

# Allow incoming HTTP, with output allowed on an established connection
$IPT -A INPUT -i eth0 -p tcp --dport 80 -m state --state NEW,ESTABLISHED -j ACCEPT
# NEW connections necessary for `apt-get`
$IPT -A OUTPUT -o eth0 -p tcp --sport 80 -m state --state NEW,ESTABLISHED -j ACCEPT

# Allow outgoing HTTP, with output allowed on an established connection
$IPT -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
#$IPT -A OUTPUT -p tcp --dport 80 -m state --state NEW -j ACCEPT
#$IPT -A OUTPUT -p tcp --dport 53 -m state --state NEW -j ACCEPT
#$IPT -A OUTPUT -p udp --dport 53 -m state --state NEW -j ACCEPT

# Allow incoming HTTPS, with output allowed on an established connection
$IPT -A INPUT -i eth0 -p tcp --dport 443 -m state --state NEW,ESTABLISHED -j ACCEPT
$IPT -A OUTPUT -o eth0 -p tcp --sport 443 -m state --state ESTABLISHED -j ACCEPT

# Allow outgoing SSH: Connect from this server to an outside server
# $IPT -A OUTPUT -o eth0 -p tcp --dport $SSH_PORT -m state --state NEW,ESTABLISHED -j ACCEPT
# $IPT -A INPUT -i eth0 -p tcp --sport $SSH_PORT -m state --state ESTABLISHED -j ACCEPT

# Allow outgoing SSH only to a specific network DO WE NEED THIS???
#$IPT -A OUTPUT -o eth0 -p tcp -d 192.168.101.0/24 --dport $SSH_PORT -m state --state NEW,ESTABLISHED -j ACCEPT
#$IPT -A INPUT -i eth0 -p tcp --sport $SSH_PORT -m state --state ESTABLISHED -j ACCEPT

# Allow outgoing HTTPS: helpful when using wget to install files etc.
$IPT -A OUTPUT -o eth0 -p tcp --dport 443 -m state --state NEW,ESTABLISHED -j ACCEPT
$IPT -A INPUT -i eth0 -p tcp --sport 443 -m state --state ESTABLISHED -j ACCEPT

# Allow ping from outside to inside - `x.x.x.x/32` denotes an exact IP, rather than a range
$IPT -A INPUT -s $HOME_IP/32 -p icmp -m icmp --icmp-type 8 -j ACCEPT
$IPT -A OUTPUT -p icmp --icmp-type echo-reply -j ACCEPT

# Allow packets from internal network to reach external network.
# if eth1 is connected to external network (internet)
# if eth0 is connected to internal network (192.168.1.x)
#$IPT -A FORWARD -i eth0 -o eth1 -j ACCEPT

# Allow Sendmail or Postfix
$IPT -A INPUT -i eth0 -p tcp --dport 25 -m state --state NEW,ESTABLISHED -j ACCEPT
$IPT -A OUTPUT -o eth0 -p tcp --sport 25 -m state --state ESTABLISHED -j ACCEPT

# Help reduce the effect of a DoS attack
$IPT -A INPUT -p tcp --dport 80 -m limit --limit 25/minute --limit-burst 100 -j ACCEPT

# Log dropped packets
$IPT -A INPUT -j LOGGING
$IPT -A LOGGING -m state --state INVALID -m limit --limit 5/min -j LOG --log-prefix "iptables-denied-INVALID: " --log-level 7
$IPT -A LOGGING -p icmp -m limit --limit 5/min -j LOG --log-prefix "iptables-denied-ICMP: " --log-level 7
$IPT -A LOGGING -p udp -m limit --limit 5/min -j LOG --log-prefix "iptables-denied-UDP: " --log-level 7
$IPT -A LOGGING -p tcp -m limit --limit 5/min -j LOG --log-prefix "iptables-denied-TCP: " --log-level 7
$IPT -A LOGGING -j DROP
